/*Proyecto Administración de Bases de Datos

INTEGRANTES 

Barrantes Chaves Jorge Fabián
Forrester Mora Daniel Alberto
Obando Espinoza Brettsy Vanessa
Rojas Madriz Joan Daniel 

*/

/*Creacion de Tablas*/

/*Tabla Vuelos*/

CREATE TABLE TAB_VUELOS (
    ID_VUELO NUMBER,
    ID_AVION NUMBER,
    ID_HORARIO NUMBER,
    ID_CIUDAD_PROCEDENCIA NUMBER,
    DESTINO VARCHAR2(100)
);

/*Tabla Aviones*/

CREATE TABLE TAB_AVIONES (
    ID_AVION NUMBER,
    NOMBRE VARCHAR2(35),
    MODELO VARCHAR2(35),
    AEROLINEA VARCHAR2(35)
);

/*Tabla Domicilio*/

CREATE TABLE TAB_DOMICILIO (
    ID_DOMICILIO NUMBER,
    PROVINCIA VARCHAR2(35),
    CANTON VARCHAR2(35),
    DISTRITO VARCHAR2(35)
);

/*Tabla Cliente*/

CREATE TABLE TAB_CLIENTE (
    ID_CLIENTE NUMBER,
    NOMBRE VARCHAR2(35),
    APELLIDOS VARCHAR2(35),
    CORREO VARCHAR2(35),
    NACIONALIDAD VARCHAR2(35),
    ID_DOMICILIO NUMBER
);

/*Tabla Ciudad*/

CREATE TABLE TAB_CIUDAD_PROCEDENCIA (
    ID_CIUDAD_PROCEDENCIA NUMBER,
    PAIS VARCHAR2(35),
    CIUDAD VARCHAR2(35),
    AEROPUERTO VARCHAR2(35)
);

/*Tabla Horarios*/

CREATE TABLE TAB_HORARIOS (
    ID_HORARIO NUMBER,
    FECHA DATE,
    HORA_DE_SALIDA TIMESTAMP,
    HORA_DE_LLEGADA TIMESTAMP
);

/*Tabla Reservas*/

CREATE TABLE TAB_RESERVAS (
    ID_RESERVA NUMBER,
    PRECIO NUMBER,
    ID_CLIENTE NUMBER,
    ID_VUELO NUMBER,
    ID_HORARIO NUMBER,
    DESCRIPCION VARCHAR2(100)
);

/*Creando Primary Key*/

ALTER TABLE TAB_VUELOS
ADD CONSTRAINT PK_TAB_VUELOS_ID_VUELO PRIMARY KEY (ID_VUELO);

ALTER TABLE TAB_AVIONES
ADD CONSTRAINT PK_TAB_AVIONES_ID_AVION PRIMARY KEY (ID_AVION);

ALTER TABLE TAB_DOMICILIO
ADD CONSTRAINT PK_TAB_DOMICILIO_ID_DOMICILIO PRIMARY KEY (ID_DOMICILIO);

ALTER TABLE TAB_CLIENTE
ADD CONSTRAINT PK_TAB_CLIENTE_ID_CLIENTE PRIMARY KEY (ID_CLIENTE);

ALTER TABLE TAB_CIUDAD_PROCEDENCIA
ADD CONSTRAINT PK_TAB_CIUDAD_PROCEDENCIA_ID_CIUDAD_PROCEDENCIA PRIMARY KEY (ID_CIUDAD_PROCEDENCIA);

ALTER TABLE TAB_HORARIOS
ADD CONSTRAINT PK_TAB_HORARIOS_ID_HORARIO PRIMARY KEY (ID_HORARIO);

/*Creando Foreign Key*/

ALTER TABLE TAB_VUELOS
ADD CONSTRAINT FK_TAB_VUELOS_ID_HORARIO FOREIGN KEY (ID_HORARIO)
REFERENCES TAB_HORARIOS(ID_HORARIO);

ALTER TABLE TAB_VUELOS
ADD CONSTRAINT FK_TAB_VUELOS_ID_CIUDAD_PROCEDENCIA FOREIGN KEY (ID_CIUDAD_PROCEDENCIA)
REFERENCES TAB_CIUDAD_PROCEDENCIA(ID_CIUDAD_PROCEDENCIA);

/**/

ALTER TABLE TAB_CLIENTE
ADD CONSTRAINT FK_TAB_CLIENTE_ID_DOMICILIO FOREIGN KEY (ID_DOMICILIO)
REFERENCES TAB_DOMICILIO(ID_DOMICILIO);

ALTER TABLE TAB_RESERVAS
ADD CONSTRAINT FK_TAB_RESERVAS_ID_CLIENTE FOREIGN KEY (ID_CLIENTE)
REFERENCES TAB_CLIENTE(ID_CLIENTE);

ALTER TABLE TAB_RESERVAS
ADD CONSTRAINT FK_TAB_RESERVAS_ID_VUELO FOREIGN KEY (ID_VUELO)
REFERENCES TAB_VUELOS(ID_VUELO);